### ISSUE TITLE
Cavallax with the cloud example is not working

### ISSUE THREAD

**Issue by zivl** [shshaw/Canvallax.js#1]
I took the example shown in codepen: http://codepen.io/shshaw/pen/ZbExyV 
and I get an error: `Canvallax.js:80 Uncaught TypeError: Cannot read property 'scrollLeft' of null`
Looks like the line `body = doc.body` gets a `null` since `doc.body` is `null`

without changing anything, just copying the example from there and it is not working.
my `html` looks like that (I omitted the `html` and `head` tags):

```
<body>
<script>
var can = Canvallax({
        className: 'bg-canvas',
        damping: 40
    });
/* then the //Clouds part and the rest of the Canvallax example */
</script>
</body>
```

It doesn't even get to the clouds part... What am I missing??

**Comment by zivl** [comment]
ohh.... After debugging a bit more, I realized that I should put this line:
`<script src="http://brokensquare.com/Code/Canvallax.js/dist/Canvallax.js"></script>`
after the `body` tag and not as part of the `head` tag

**Comment by shshaw** [comment]
Ah yes, glad you figured it out.

It's best to include scripts at the very end, right before the `</body>` tag so scripts won't prevent the browser from rendering the rest of the page. I developed Canvallax with that in mind, but I believe I've added a check for this in Canvallax 2 to prevent the same error.

**Comment by shshaw** [comment]
Also: I'd love to see how you use Canvallax. Shoot me a link to your project if/when it's public! Let me know if you have any questions.
